= Chan Han Yen, Chinese Student
Sui Sin Far
:date: January 1912
:publication: New England Magazine
:location: Boston
:volumenum: Vol. 45, No. 5
:pages: 462-466
:stylesheet: ../../styles/tufte.css
:nofooter:

include::../../styles/css.adoc[]
include::../../notes/notes.adoc[]

[[page_462]]
== I.

HE was Han Yen of the family of Chan, from the town of Choo-Chow{sn-chan-choochow}, in the Province of Kiangsoo{sn-chan-kiangsoo}. His father was a schoolmaster, so also had been his grandfather, and his great grandfather before him. He was chosen out of three sons to be the scholar of the family, and during his boyhood studied diligently and with ambition. From school to college he passed, and at the age of twenty, took successfully the examinations which entitled him to a western education at government expense.

One of a band of Chinese youths he came to America and entered an American University. The new life and the new environment interested and exhilarated him. His most earnest desire was to absorb every good element of western education, so that he might be able to return to the Motherland well equipped to render her good service. He fully believed that he and his compatriot students were the destined future leaders of China, and his ambition to add lustre to the name of Chan, was almost holy.

The American widow with whom he boarded described him to her friends and neighbors as the best of all Chinese students. "And you know," she added with almost family pride, "the Chinese have the reputation of being the best students of all."

The widow, whose name was Mrs. Caroline Bray, had a daughter named Carrie. Carrie was a pretty girl of nineteen, with eyes and hair almost as dark[[page_463]] as the eyes and hair of the little girl who had been adopted by Han Yen's parents to become his future wife. For seven months Carrie paid little attention to Han Yen. Her time was well occupied with housework, and in the evenings and Sundays, there was the Chinese Mission. Besides there were other students in the house.

It was one evening in early spring. The other Chinese students were dining a member of the Legation at a Chinese restaurant in the city, and Han Yen, who was unacquainted with the official, was alone with Mrs. Bray and her daughter. Mrs. Bray had been talking cheerily during the meal and Carrie had occasionally joined in. When Han Yen finally arose and was about to ascend the stairs to his room, the girl looked up with a smile and bade him not study too hard.

"What should I do with myself if I did not study?" asked Han Yen.

"Well," suggested Carrie brightly, "you might, for instance, come with me to the Chinese Mission sociable."

Han Yen had never before taken a walk with a young woman, but he had heard a paper read by a senior student, in which it had been stated that chatting with members of the fair sex, even though folly was their theme, should be part of the Chinese student's American curriculum. So politely expressing his pleasure at being permitted to accompany Miss Carrie, the boy put on his hat and solemnly walked down the street beside her.

Suddenly she began to laugh.

"What is amusing you?" he enquired.

"You walk too far away," she replied, "one would think you were afraid of me."

Han Yen, blushing and embarrassed, but desirous above all things of conforming to what was right and proper according to western ideas, lessened the distance between him and his companion.

The evening passed pleasantly if somewhat bewilderingly. On the way home the student learned from the youthful and self constituted missionary that through her instrumentality over one hundred Chinese boys had become acquainted with the English language and converted to Christianity.

"In behalf of my countrymen in America, accept my heartfelt gratitude," replied Han Yen.

The next afternoon, he repeated to his cousin, Chan Han Fong, what Miss Carrie had told him, adding: "I feel ashamed that a young female should be able to do so much more than I for the cause of humanity."

Though to Han Yen, Confucianist, the Missions certainly did not appeal as Temples of Ethical Culture, he was well able to appreciate the fact that they were the only bright spots in the lives of his laboring compatriots, exiles from their own homes and families.

After that evening Han Yen was invited occasionally to sit in the parlor of the widow Bray, where he listened to Carrie talking, playing, singing and otherwise entertaining her Chinese company. She was neither a clever nor well educated girl; but she was bright and attractive, and such as she was, dazzled the young student, to whom everything western, including women, was wonderful and worshipful.

One evening Carrie and Han Yen were alone. The girl was playing some sentimental melodies. The boy felt very happy. He always did feel happy when he was alone with Carrie. it was different when the other students were present, and Carrie smiled, first at this one, and then at that. Han Yen had not analyzed the painful sensations which took possession of him whenever Carrie smiled or spoke in friendly or familiar fashion to another student. On one occasion, however, these feelings had so overpowered him that he had risen abruptly from his seat and left the room. "Where are you going, Mr. Chan?" Carrie had called after him, and with innocent rudeness, he had replied: "To where you are not."

Carrie had returned to the room, demure and smiling. She understood Chinese students much better than they understood her, learned though they were and simple though she was.

This evening, for instance, she was fairly conscious of Han Yen's state of mind, and as she was a good natured little thing, continued playing for him for[[page_464]] some time. Finally, she arose from the piano stool, and going over to the table on which stood a jar of hothouse flowers, took therefrom a piece of heliotrope.

"It was awfully sweet of you, Mr. Chan," said she, sniffing at the spray, "to bring me such beautiful flowers, and heliotrope is my favorite."

"It is very fragrant," murmured Han Yen.

"I had my fortune told yesterday," said Carrie, standing before the old fashioned mirror and fastening the flower in her hair.

"Was it a good one?" enquired the boy. Ordinarily he had no faith and little interest in mystical lore.

"I don't know," replied the girl, "it was rather funny, though. I don't think, Mr. Chan, that I shall tell you."

"I wish you would," urged Han Yen earnestly.

"Well, then, it was this: that my future husband would be a foreigner, and that he would bring me to-day a bouquet of flowers in which there would be one that was neither pink, yellow, green, blue nor red."

== II.

When Chan Han Fong learned that his cousin loved a woman of the white race, and was resolved to do as the American men do when they fall in love, his face became pallid.

"What!" he cried, "you will relinquish your sacred ambition to work for China, dishonor your ancestors, disregard your parents' wishes, and set at naught your betrothal to the daughter of Tien Wang -- all for sake of a woman of alien blood?"

"Yes," declared Han Yen, his face shining, "love is more than all."

"You have gone mad," cried Chan Han Fong, "think of the sorrow and disgrace which you will bring upon all to whom you are bound by the ties of relationship, gratitude and affection. Is a feeling which obliterates and destroys every virtuous thought and sentiment, worth cherishing?"

"The feeling which possesses me," replied Han Yen, "is divine."

Chan Han Fong stepped to his desk and took therefrom a paper: "Listen," said he, "six months ago you wrote:

[verse, subs="quotes,attributes"]
____
Oh, China, misguided country!
What would I not sacrifice,
To see thee uphold thyself,
Among the nations,
For bitterer than death, 'tis to know,
That thou that wert more glorious than all,
Now lieth as low as the lowest,
Whilst the feet of those whom thou didst despise,
Rest insolently upon thy limbs,
The Middle Kingdom{sn-chan-middle} wert thou called,
The country that Heaven loves,
Thou wert the birthplace of the arts, the sciences,
And all mankind blessing inventions,
Thy princes rested in benevolence,
Thy wise men were revered,
Thy people happy.
But now, the empire which is the oldest
under the heavens is falling,
And lesser nations stand ready to smite,
The nation that first smote itself,
Truly Mencius has said{sn-chan-mencius}:
'The loss of the empire comes through
losing the hearts of the people.'
The hearts of the people being lost,
Who shall restore the Empire?"
____

Silence followed this declamation. Chan Han Yen's face fell, bowed upon his hands.

"Alas for China!" exclaimed Chan Han Fong, his own young eyes glowing with fateful fire. "When those who know how she can and must be saved -- the very ones who could and should be her saviours -- turn traitor to her."

The bowed head was lifted.

"Oh, Fong," plead Han Yen, "I can no more be as I have been. The aim and purpose of my existence has changed. And what is one student to China?"

"Why are you here?" sternly demanded Chan Han Fong. Then, because his young cousin was dear to him, he went over to where the boy leaned, and laying his arm around his shoulder, pleaded with him thus:

"See, my cousin! The flowers of the fields and of the woods and dales! Those of a kind come up together. The sister violet companions her brother. Only[[page_465]] through some mistake in the seeding is it otherwise. And the hybrid flower, though beautiful, is the saddest flower of all."

Han Yen trembled.

At that moment a girl's voice floated through the window.

"Yen, Yen," it called, "I want you to go into town with me."

Han Yen shook off his cousin's detaining hand.

"Pardon me," said he, "but I must go."

"Ah!" soliloquized Chan Han Fong, gazing sadly after him. "A low caste American girl has disordered his mind."

The year before Han Yen had come to the University, Han Fong had been invited, with several other Chinese students, to spend an afternoon at the home of a wealthy and cultured maiden lady who lived on the other side of the river. This lady, who was white haired, soft voiced and comprehending, had entertained the Chinese youths in what to them, was a most delightful fashion. Han Fong had never forgotten that afternoon, nor one who had been a part of and in harmony with it -- a young girl, almost a child in years, tall and slender, with thoughtful eyes and quiet ways. That young girl had not belittled the foreign students by flirting with and plying them with numerous personal questions; but Han Fong had taken note that she had listened with interest while their hostess charmed them to talk of their work and aspirations, and that the few remarks which she had made, were intelligent, and proved, that young though she was, she understood the purpose of their lives and sympathised with it.

Because of that young girl, seen and heard but once, Chan Han Fong, called Carrie Bray, "low caste."

== III.

Carrie had returned home tired out with a day's watching by the bedside of a sick Chinese woman.

"Why are you so good to everybody but yourself?" enquired Han Yen, meeting the girl as she entered the house in the dusk of the evening and following her into the sitting room.

"I _am_ good to myself," answered Carrie cheerfully. "I'm accustomed to helping the poor Chinese. Indeed, I don't know what I shall do with myself after I give them up for you, Yen."

"I shall not require you to give them up altogether," replied the boy tenderly, "It is a work for humanity which you are doing and I hope to be able to help you with it."

"Why, dearie, what are you talking about?" exclaimed Carrie.

"About -- when we shall be happy."

"You mean -- when we go to China."

"No -- here. I cannot go back to China for many years -- perhaps never."

"Why?"

Carrie's voice sounded sharp.

"Because I must work for my living -- and for yours," answered the boy, "and if I were to return to China I would have to work for the government until I had repaid what I owed for my education here."

"Oh! Then you are not rich!"

"Rich!" echoed Han Yen. "My father had to sell his land to enable me to complete my studies. Otherwise I would not have been able to compete at the Pekin examinations{sn-chan-pekin}."

"You always used to say that you were going back to China."

"Yes," said Han Yen. "It was my great ambition to return to China and work for her -- and alone I could have done so. But now, I shall not be alone -- and I have a higher and loftier ambition than to work for China -- it is to work for humanity -- with you."

"I do not understand you," gasped Carrie.

"But you will," said Han Yen. "Listen. I have yet to tell you how much I love you, and how all my heart is weeping and laughing for you. I am giving up all for you, to be with you, to work for you. I am not returning to my native land, because all my thought is you -- and everything else is as naught."

The girl shrank before the rising emotion in the boy's face and voice.

"Good night, Yen, dear," said she, her hand upon the door knob, "I am so tired that I can't sit up one moment longer. See you to-morrow."

And then she stole away to the kitchen and said to her mother:[[page_466]]

"What do you think? Yen's people are poor and after we are married, he will have to stay in America and live and work here just like a common Chinaman."

"Lands sakes!" ejaculated Mrs. Bray. "Ain't that awful! And I've been telling all around that you was to marry a Chinese gentleman and was to go to China and live in great style!"

"And he isn't a Christian either," murmured Carrie.

== IV.

[verse]
____
"Dear Friend:

Mother and I have been talking over things, and we have both decided that it would not be right for me to marry a man who is not a Christian. I am very sorry. I am going into town for a few days.

Your affectionate friend,
Carrie Bray."
____


Chan Han Yen read the little note over many times. Finally he folded it, put it back into its envelope and slipped it under the rubber band which bound together a neat bundle of letters lying on his desk.

Then he went out into the night. He did not know where he was going. All he knew was that the girl who had altered his life and driven everything else out of it, had cast him aside, because, oh, _not_ because of the reason she had given. Chan Han Yen, Chinese student, was wiser than Carrie Bray in that respect.

His rage and mortification, his distress was indescribable. As he walked along he clenched his hands so that his nails sunk into his soft palms and the blood trickled down. He was only twenty-one.

Thus till morning dawned. The birds had begun to twitter when a turn in the road revealed a little hamlet lying in the semi-darkness of a valley. It was a peaceful scene and brought before the boy's mind his own home so far away -- the home that he had been willing to cut himself away from forever. It seemed to him that he could see his father and his mother, his brothers, and the sweet little adopted daughter of the family. Yes, all the dear people who had been so proud of him, and who, one and all, had made so many sacrifices that he, the scholar, the talented one, might travel far and bring back to the east the wisdom of the west. To him they had trusted and were trusting, to reflect honor and glory upon them and their country.

And he! Chan Han Yen threw himself down upon the soft turf. All anger and passion were spent; but in their place what shame and abasement of spirit! The air was sweet with the scent of the earth; the leaves hung silently on the bushes near by. Chan Han Yen fell asleep.

When he awoke the sun was well up. He turned his face to its brightness.

"Good morning, benign friend," said he, "the Lesson of the Woman is over."

[.publication-source]
— {date}. _{publication}_, {volumenum}, pp. {pages}.
